// Auto-generated route configuration
// This file is automatically generated by the route-generator plugin
// Do not edit manually - your changes will be overwritten

import Route1 from '../contents/apps/index.mdx'
import Route2 from '../contents/deployment/index.mdx'
import Route3 from '../contents/getting-started.md'
import Route0 from '../contents/index.mdx'
import Route5 from '../contents/manifest_builder/api-reference.mdx'
import Route6 from '../contents/manifest_builder/cli-usage.mdx'
import Route7 from '../contents/manifest_builder/configuration.mdx'
import Route8 from '../contents/manifest_builder/development.mdx'
import Route4 from '../contents/manifest_builder/index.mdx'
import Route9 from '../contents/manifest_builder/storage-providers.mdx'

export interface RouteConfig {
  path: string
  component: React.ComponentType
  title: string
  meta: Record<string, unknown>
}

export const routes: RouteConfig[] = [
  {
    path: '/',
    component: Route0,
    title: 'Overview',
    meta: {
      title: 'Overview',
      createdAt: '2025-07-20T22:35:03+08:00',
      lastModified: '2025-07-20T22:35:03+08:00',
    },
  },
  {
    path: '/apps',
    component: Route1,
    title: 'Apps Package',
    meta: {
      title: 'Apps Package',
      description: 'Afilmory Apps package includes static web and ssr runtime.',
      createdAt: '2025-07-20T22:35:03+08:00',
      lastModified: '2025-07-20T22:35:03+08:00',
    },
  },
  {
    path: '/deployment',
    component: Route2,
    title: 'Deployment',
    meta: {
      title: 'Deployment',
      description:
        'Guide to deploying Afilmory Builder in production environments, including Docker and configuration options.',
      createdAt: '2025-07-20T22:35:03+08:00',
      lastModified: '2025-07-20T22:35:03+08:00',
    },
  },
  {
    path: '/getting-started',
    component: Route3,
    title: 'Getting Started',
    meta: {
      title: 'Getting Started',
      createdAt: '2025-07-20T22:35:03+08:00',
      lastModified: '2025-07-20T22:35:03+08:00',
    },
  },
  {
    path: '/manifest_builder',
    component: Route4,
    title: 'Manifest Builder',
    meta: {
      title: 'Manifest Builder',
      description:
        'Afilmory Builder is a high-performance photo processing and indexing system that supports multiple storage backends and concurrent processing modes.',
      createdAt: '2025-07-20T22:35:03+08:00',
      lastModified: '2025-07-20T22:35:03+08:00',
    },
  },
  {
    path: '/manifest_builder/api-reference',
    component: Route5,
    title: 'API Reference',
    meta: {
      title: 'API Reference',
      description:
        'Complete API reference for integrating Afilmory Builder into your applications and extending its functionality.',
      createdAt: '2025-07-20T22:35:03+08:00',
      lastModified: '2025-07-20T22:35:03+08:00',
    },
  },
  {
    path: '/manifest_builder/cli-usage',
    component: Route6,
    title: 'Command Line Usage',
    meta: {
      title: 'Command Line Usage',
      description:
        'Complete guide to using the Afilmory Builder CLI for photo processing and manifest generation.',
      createdAt: '2025-07-20T22:35:03+08:00',
      lastModified: '2025-07-20T22:35:03+08:00',
    },
  },
  {
    path: '/manifest_builder/configuration',
    component: Route7,
    title: 'Configuration Guide',
    meta: {
      title: 'Configuration Guide',
      description:
        'Complete guide to configuring Afilmory Builder for different storage backends and performance scenarios.',
      createdAt: '2025-07-20T22:35:03+08:00',
      lastModified: '2025-07-20T22:35:03+08:00',
    },
  },
  {
    path: '/manifest_builder/development',
    component: Route8,
    title: 'Development Guide',
    meta: {
      title: 'Development Guide',
      description:
        'Guide for developers who want to contribute to or extend the Afilmory Builder package.',
      createdAt: '2025-07-20T22:35:03+08:00',
      lastModified: '2025-07-20T22:35:03+08:00',
    },
  },
  {
    path: '/manifest_builder/storage-providers',
    component: Route9,
    title: 'Storage Providers',
    meta: {
      title: 'Storage Providers',
      description:
        'Comprehensive guide to configuring and using different storage backends with Afilmory Builder.',
      createdAt: '2025-07-20T22:35:03+08:00',
      lastModified: '2025-07-20T22:35:03+08:00',
    },
  },
]

export default routes
