// Auto-generated route configuration
// This file is automatically generated by the route-generator plugin
// Do not edit manually - your changes will be overwritten

import Route2 from '../contents/deployment/docker.mdx'
import Route1 from '../contents/deployment/index.mdx'
import Route0 from '../contents/index.mdx'

export interface RouteConfig {
  path: string
  component: React.ComponentType
  title: string
  meta: Record<string, unknown>
}

export const routes: RouteConfig[] = [
  {
    path: '/',
    component: Route0,
    title: 'Overview',
    meta: {
      title: 'Overview',
      createdAt: '2025-07-20T22:35:03+08:00',
      lastModified: '2025-07-20T22:35:03+08:00',
    },
  },
  {
    path: '/deployment',
    component: Route1,
    title: 'Deployment',
    meta: {
      title: 'Deployment',
      description:
        'Guide to deploying Afilmory in production environments, including Docker and configuration options.',
      createdAt: '2025-07-20T22:35:03+08:00',
      lastModified: '2025-08-08T08:28:42.778+08:00',
    },
  },
  {
    path: '/deployment/docker',
    component: Route2,
    title: 'Docker',
    meta: {
      title: 'Docker',
      description: 'Guide to deploying Afilmory via Docker.',
      createdAt: '2025-07-20T22:35:03+08:00',
      lastModified: '2025-08-08T08:28:42.778+08:00',
    },
  },
]

export default routes
