// This file is automatically generated by the toc-extractor plugin
// Do not edit manually

export interface TocItem {
  id: string
  level: number
  text: string
  children?: TocItem[]
}

export interface FileToc {
  file: string
  path: string
  title: string
  toc: TocItem[]
}

export const tocData: FileToc[] = [
  {
    file: 'index.mdx',
    path: '/',
    title: 'Overview',
    toc: [
      {
        id: 'overview',
        level: 1,
        text: 'Overview',
        children: [
          {
            id: 'features',
            level: 2,
            text: '🌟 Features',
            children: [
              {
                id: 'core-functionality',
                level: 3,
                text: 'Core Functionality',
                children: [],
              },
              {
                id: 'image-processing',
                level: 3,
                text: 'Image Processing',
                children: [],
              },
              {
                id: 'advanced-features',
                level: 3,
                text: 'Advanced Features',
                children: [],
              },
            ],
          },
          {
            id: 'technical-architecture',
            level: 2,
            text: '🏗️ Technical Architecture',
            children: [
              {
                id: 'frontend-tech-stack',
                level: 3,
                text: 'Frontend Tech Stack',
                children: [],
              },
              {
                id: 'build-system',
                level: 3,
                text: 'Build System',
                children: [],
              },
              {
                id: 'storage-architecture',
                level: 3,
                text: 'Storage Architecture',
                children: [],
              },
            ],
          },
          {
            id: 'quick-start',
            level: 2,
            text: '🚀 Quick Start',
            children: [
              {
                id: 'docker-deployment',
                level: 3,
                text: 'Docker Deployment',
                children: [],
              },
            ],
          },
          {
            id: 'configuration-options',
            level: 2,
            text: '⚙️ Configuration Options',
            children: [
              {
                id: 'remote-repository-configuration-repo',
                level: 4,
                text: 'Remote Repository Configuration (`repo`)',
                children: [],
              },
              {
                id: 'storage-configuration-storage',
                level: 4,
                text: 'Storage Configuration (`storage`)',
                children: [],
              },
              {
                id: 'build-options-options',
                level: 4,
                text: 'Build Options (`options`)',
                children: [],
              },
              {
                id: 'performance-configuration-performance',
                level: 4,
                text: 'Performance Configuration (`performance`)',
                children: [],
              },
              {
                id: 'logging-configuration-logging',
                level: 4,
                text: 'Logging Configuration (`logging`)',
                children: [],
              },
            ],
          },
          {
            id: 'cli-commands',
            level: 2,
            text: '📋 CLI Commands',
            children: [
              {
                id: 'build-commands',
                level: 3,
                text: 'Build Commands',
                children: [],
              },
              {
                id: 'development-commands',
                level: 3,
                text: 'Development Commands',
                children: [],
              },
              {
                id: 'notes',
                level: 3,
                text: 'Notes',
                children: [],
              },
            ],
          },
          {
            id: 'advanced-usage',
            level: 2,
            text: '🔧 Advanced Usage',
            children: [
              {
                id: 'custom-storage-provider',
                level: 3,
                text: 'Custom Storage Provider',
                children: [],
              },
              {
                id: 'custom-image-processing',
                level: 3,
                text: 'Custom Image Processing',
                children: [],
              },
            ],
          },
          {
            id: 'license',
            level: 2,
            text: '📄 License',
            children: [],
          },
          {
            id: 'related-links',
            level: 2,
            text: '🔗 Related Links',
            children: [],
          },
        ],
      },
    ],
  },
  {
    file: 'apps/index.mdx',
    path: '/apps',
    title: 'Apps Package',
    toc: [
      {
        id: 'apps-package',
        level: 1,
        text: 'Apps Package',
        children: [],
      },
    ],
  },
  {
    file: 'deployment/index.mdx',
    path: '/deployment',
    title: 'Deployment',
    toc: [
      {
        id: 'deployment',
        level: 1,
        text: 'Deployment',
        children: [],
      },
    ],
  },
  {
    file: 'getting-started.md',
    path: '/getting-started',
    title: 'Getting Started',
    toc: [
      {
        id: 'getting-started',
        level: 1,
        text: 'Getting Started',
        children: [
          {
            id: 'features',
            level: 2,
            text: 'Features',
            children: [],
          },
          {
            id: 'quick-start',
            level: 2,
            text: 'Quick Start',
            children: [],
          },
        ],
      },
    ],
  },
  {
    file: 'manifest_builder/index.mdx',
    path: '/manifest_builder',
    title: 'Manifest Builder',
    toc: [
      {
        id: 'manifest-builder',
        level: 1,
        text: 'Manifest Builder',
        children: [
          {
            id: 'core-features',
            level: 2,
            text: 'Core Features',
            children: [
              {
                id: 'photo-processing',
                level: 3,
                text: '📸 Photo Processing',
                children: [],
              },
              {
                id: 'image-analysis',
                level: 3,
                text: '🎨 Image Analysis',
                children: [],
              },
              {
                id: 'storage-support',
                level: 3,
                text: '🗄️ Storage Support',
                children: [],
              },
              {
                id: 'performance-optimization',
                level: 3,
                text: '⚡ Performance Optimization',
                children: [],
              },
            ],
          },
          {
            id: 'architecture-design',
            level: 2,
            text: 'Architecture Design',
            children: [
              {
                id: 'core-modules',
                level: 3,
                text: 'Core Modules',
                children: [],
              },
            ],
          },
          {
            id: 'use-cases',
            level: 2,
            text: 'Use Cases',
            children: [
              {
                id: '1-photo-library-building',
                level: 3,
                text: '1. Photo Library Building',
                children: [],
              },
              {
                id: '2-batch-photo-processing',
                level: 3,
                text: '2. Batch Photo Processing',
                children: [],
              },
              {
                id: '3-storage-migration',
                level: 3,
                text: '3. Storage Migration',
                children: [],
              },
            ],
          },
          {
            id: 'key-features',
            level: 2,
            text: 'Key Features',
            children: [],
          },
          {
            id: 'configuration-example',
            level: 2,
            text: 'Configuration Example',
            children: [],
          },
          {
            id: 'output-format',
            level: 2,
            text: 'Output Format',
            children: [],
          },
        ],
      },
    ],
  },
  {
    file: 'manifest_builder/api-reference.mdx',
    path: '/manifest_builder/api-reference',
    title: 'API Reference',
    toc: [
      {
        id: 'api-reference',
        level: 1,
        text: 'API Reference',
        children: [
          {
            id: 'core-api',
            level: 2,
            text: 'Core API',
            children: [
              {
                id: 'builder-class',
                level: 3,
                text: 'Builder Class',
                children: [
                  {
                    id: 'constructor',
                    level: 4,
                    text: 'Constructor',
                    children: [],
                  },
                  {
                    id: 'methods',
                    level: 4,
                    text: 'Methods',
                    children: [
                      {
                        id: 'buildoptions',
                        level: 5,
                        text: '`build(options?)`',
                        children: [],
                      },
                      {
                        id: 'validateoptions',
                        level: 5,
                        text: '`validate(options?)`',
                        children: [],
                      },
                      {
                        id: 'cleanupoptions',
                        level: 5,
                        text: '`cleanup(options?)`',
                        children: [],
                      },
                    ],
                  },
                ],
              },
            ],
          },
          {
            id: 'configuration-interfaces',
            level: 2,
            text: 'Configuration Interfaces',
            children: [
              {
                id: 'builderconfig',
                level: 3,
                text: 'BuilderConfig',
                children: [],
              },
              {
                id: 'storageconfig',
                level: 3,
                text: 'StorageConfig',
                children: [],
              },
              {
                id: 'performanceconfig',
                level: 3,
                text: 'PerformanceConfig',
                children: [],
              },
            ],
          },
          {
            id: 'photo-processing-api',
            level: 2,
            text: 'Photo Processing API',
            children: [
              {
                id: 'photoprocessor',
                level: 3,
                text: 'PhotoProcessor',
                children: [
                  {
                    id: 'methods',
                    level: 4,
                    text: 'Methods',
                    children: [
                      {
                        id: 'processphotofile-options',
                        level: 5,
                        text: '`processPhoto(file, options?)`',
                        children: [],
                      },
                      {
                        id: 'generatethumbnailsphoto-sizes',
                        level: 5,
                        text: '`generateThumbnails(photo, sizes?)`',
                        children: [],
                      },
                      {
                        id: 'extractmetadatafile',
                        level: 5,
                        text: '`extractMetadata(file)`',
                        children: [],
                      },
                    ],
                  },
                ],
              },
              {
                id: 'image-analysis-api',
                level: 3,
                text: 'Image Analysis API',
                children: [
                  {
                    id: 'thumbhash-generation',
                    level: 4,
                    text: 'ThumbHash Generation',
                    children: [],
                  },
                  {
                    id: 'tone-analysis',
                    level: 4,
                    text: 'Tone Analysis',
                    children: [],
                  },
                  {
                    id: 'histogram-generation',
                    level: 4,
                    text: 'Histogram Generation',
                    children: [],
                  },
                ],
              },
            ],
          },
          {
            id: 'storage-api',
            level: 2,
            text: 'Storage API',
            children: [
              {
                id: 'storage-providers',
                level: 3,
                text: 'Storage Providers',
                children: [],
              },
              {
                id: 'storage-interface',
                level: 3,
                text: 'Storage Interface',
                children: [],
              },
            ],
          },
          {
            id: 'worker-api',
            level: 2,
            text: 'Worker API',
            children: [
              {
                id: 'cluster-processing',
                level: 3,
                text: 'Cluster Processing',
                children: [],
              },
              {
                id: 'thread-pool-processing',
                level: 3,
                text: 'Thread Pool Processing',
                children: [],
              },
            ],
          },
          {
            id: 'manifest-api',
            level: 2,
            text: 'Manifest API',
            children: [
              {
                id: 'manifest-management',
                level: 3,
                text: 'Manifest Management',
                children: [],
              },
              {
                id: 'manifest-schema',
                level: 3,
                text: 'Manifest Schema',
                children: [],
              },
            ],
          },
          {
            id: 'event-system',
            level: 2,
            text: 'Event System',
            children: [
              {
                id: 'available-events',
                level: 3,
                text: 'Available Events',
                children: [],
              },
            ],
          },
          {
            id: 'extensions-and-plugins',
            level: 2,
            text: 'Extensions and Plugins',
            children: [
              {
                id: 'creating-custom-processors',
                level: 3,
                text: 'Creating Custom Processors',
                children: [],
              },
              {
                id: 'creating-storage-providers',
                level: 3,
                text: 'Creating Storage Providers',
                children: [],
              },
            ],
          },
          {
            id: 'utility-functions',
            level: 2,
            text: 'Utility Functions',
            children: [
              {
                id: 'file-utilities',
                level: 3,
                text: 'File Utilities',
                children: [],
              },
              {
                id: 'image-utilities',
                level: 3,
                text: 'Image Utilities',
                children: [],
              },
            ],
          },
          {
            id: 'error-handling',
            level: 2,
            text: 'Error Handling',
            children: [],
          },
          {
            id: 'typescript-support',
            level: 2,
            text: 'TypeScript Support',
            children: [],
          },
        ],
      },
    ],
  },
  {
    file: 'manifest_builder/cli-usage.mdx',
    path: '/manifest_builder/cli-usage',
    title: 'Command Line Usage',
    toc: [
      {
        id: 'command-line-usage',
        level: 1,
        text: 'Command Line Usage',
        children: [
          {
            id: 'basic-commands',
            level: 2,
            text: 'Basic Commands',
            children: [
              {
                id: 'build-command',
                level: 3,
                text: 'Build Command',
                children: [],
              },
              {
                id: 'common-options',
                level: 3,
                text: 'Common Options',
                children: [],
              },
            ],
          },
          {
            id: 'advanced-options',
            level: 2,
            text: 'Advanced Options',
            children: [
              {
                id: 'processing-control',
                level: 3,
                text: 'Processing Control',
                children: [],
              },
              {
                id: 'file-filtering',
                level: 3,
                text: 'File Filtering',
                children: [],
              },
              {
                id: 'output-control',
                level: 3,
                text: 'Output Control',
                children: [],
              },
            ],
          },
          {
            id: 'specialized-commands',
            level: 2,
            text: 'Specialized Commands',
            children: [
              {
                id: 'validation-commands',
                level: 3,
                text: 'Validation Commands',
                children: [],
              },
              {
                id: 'maintenance-commands',
                level: 3,
                text: 'Maintenance Commands',
                children: [],
              },
              {
                id: 'migration-commands',
                level: 3,
                text: 'Migration Commands',
                children: [],
              },
            ],
          },
          {
            id: 'configuration-options',
            level: 2,
            text: 'Configuration Options',
            children: [
              {
                id: 'config-file-selection',
                level: 3,
                text: 'Config File Selection',
                children: [],
              },
              {
                id: 'runtime-configuration',
                level: 3,
                text: 'Runtime Configuration',
                children: [],
              },
            ],
          },
          {
            id: 'monitoring-and-logging',
            level: 2,
            text: 'Monitoring and Logging',
            children: [
              {
                id: 'progress-monitoring',
                level: 3,
                text: 'Progress Monitoring',
                children: [],
              },
              {
                id: 'logging-options',
                level: 3,
                text: 'Logging Options',
                children: [],
              },
            ],
          },
          {
            id: 'examples',
            level: 2,
            text: 'Examples',
            children: [
              {
                id: 'development-workflow',
                level: 3,
                text: 'Development Workflow',
                children: [],
              },
              {
                id: 'production-deployment',
                level: 3,
                text: 'Production Deployment',
                children: [],
              },
              {
                id: 'troubleshooting',
                level: 3,
                text: 'Troubleshooting',
                children: [],
              },
            ],
          },
          {
            id: 'environment-variables',
            level: 2,
            text: 'Environment Variables',
            children: [],
          },
          {
            id: 'exit-codes',
            level: 2,
            text: 'Exit Codes',
            children: [],
          },
          {
            id: 'scripting-and-automation',
            level: 2,
            text: 'Scripting and Automation',
            children: [
              {
                id: 'github-actions-example',
                level: 3,
                text: 'GitHub Actions Example',
                children: [],
              },
              {
                id: 'cron-job-example',
                level: 3,
                text: 'Cron Job Example',
                children: [],
              },
            ],
          },
          {
            id: 'getting-help',
            level: 2,
            text: 'Getting Help',
            children: [],
          },
        ],
      },
    ],
  },
  {
    file: 'manifest_builder/configuration.mdx',
    path: '/manifest_builder/configuration',
    title: 'Configuration Guide',
    toc: [
      {
        id: 'configuration-guide',
        level: 1,
        text: 'Configuration Guide',
        children: [
          {
            id: 'configuration-file-structure',
            level: 2,
            text: 'Configuration File Structure',
            children: [],
          },
          {
            id: 'storage-configuration',
            level: 2,
            text: 'Storage Configuration',
            children: [
              {
                id: 'amazon-s3-configuration',
                level: 3,
                text: 'Amazon S3 Configuration',
                children: [],
              },
              {
                id: 'github-storage-configuration',
                level: 3,
                text: 'GitHub Storage Configuration',
                children: [],
              },
              {
                id: 'local-storage-configuration',
                level: 3,
                text: 'Local Storage Configuration',
                children: [],
              },
            ],
          },
          {
            id: 'performance-configuration',
            level: 2,
            text: 'Performance Configuration',
            children: [
              {
                id: 'worker-configuration',
                level: 3,
                text: 'Worker Configuration',
                children: [],
              },
              {
                id: 'optimization-settings',
                level: 3,
                text: 'Optimization Settings',
                children: [],
              },
            ],
          },
          {
            id: 'general-options',
            level: 2,
            text: 'General Options',
            children: [
              {
                id: 'feature-toggles',
                level: 3,
                text: 'Feature Toggles',
                children: [],
              },
              {
                id: 'path-configuration',
                level: 3,
                text: 'Path Configuration',
                children: [],
              },
            ],
          },
          {
            id: 'environment-specific-configurations',
            level: 2,
            text: 'Environment-Specific Configurations',
            children: [
              {
                id: 'development-configuration',
                level: 3,
                text: 'Development Configuration',
                children: [],
              },
              {
                id: 'production-configuration',
                level: 3,
                text: 'Production Configuration',
                children: [],
              },
            ],
          },
          {
            id: 'configuration-validation',
            level: 2,
            text: 'Configuration Validation',
            children: [],
          },
          {
            id: 'environment-variables',
            level: 2,
            text: 'Environment Variables',
            children: [],
          },
          {
            id: 'configuration-best-practices',
            level: 2,
            text: 'Configuration Best Practices',
            children: [],
          },
        ],
      },
    ],
  },
  {
    file: 'manifest_builder/development.mdx',
    path: '/manifest_builder/development',
    title: 'Development Guide',
    toc: [
      {
        id: 'development-guide',
        level: 1,
        text: 'Development Guide',
        children: [
          {
            id: 'development-setup',
            level: 2,
            text: 'Development Setup',
            children: [
              {
                id: 'prerequisites',
                level: 3,
                text: 'Prerequisites',
                children: [],
              },
              {
                id: 'environment-setup',
                level: 3,
                text: 'Environment Setup',
                children: [],
              },
              {
                id: 'development-scripts',
                level: 3,
                text: 'Development Scripts',
                children: [],
              },
            ],
          },
          {
            id: 'project-structure',
            level: 2,
            text: 'Project Structure',
            children: [],
          },
          {
            id: 'architecture-overview',
            level: 2,
            text: 'Architecture Overview',
            children: [
              {
                id: 'core-components',
                level: 3,
                text: 'Core Components',
                children: [
                  {
                    id: '1-builder-core-srcbuilder',
                    level: 4,
                    text: '1. Builder Core (`src/builder/`)',
                    children: [],
                  },
                  {
                    id: '2-storage-layer-srcstorage',
                    level: 4,
                    text: '2. Storage Layer (`src/storage/`)',
                    children: [],
                  },
                  {
                    id: '3-photo-processing-srcphoto',
                    level: 4,
                    text: '3. Photo Processing (`src/photo/`)',
                    children: [],
                  },
                  {
                    id: '4-image-analysis-srcimage',
                    level: 4,
                    text: '4. Image Analysis (`src/image/`)',
                    children: [],
                  },
                  {
                    id: '5-worker-management-srcworker',
                    level: 4,
                    text: '5. Worker Management (`src/worker/`)',
                    children: [],
                  },
                ],
              },
              {
                id: 'data-flow',
                level: 3,
                text: 'Data Flow',
                children: [],
              },
            ],
          },
          {
            id: 'development-workflows',
            level: 2,
            text: 'Development Workflows',
            children: [
              {
                id: 'adding-a-new-storage-provider',
                level: 3,
                text: 'Adding a New Storage Provider',
                children: [],
              },
              {
                id: 'adding-image-analysis-features',
                level: 3,
                text: 'Adding Image Analysis Features',
                children: [],
              },
              {
                id: 'performance-optimization',
                level: 3,
                text: 'Performance Optimization',
                children: [
                  {
                    id: 'profiling',
                    level: 4,
                    text: 'Profiling',
                    children: [],
                  },
                  {
                    id: 'memory-management',
                    level: 4,
                    text: 'Memory Management',
                    children: [],
                  },
                ],
              },
            ],
          },
          {
            id: 'testing',
            level: 2,
            text: 'Testing',
            children: [
              {
                id: 'test-structure',
                level: 3,
                text: 'Test Structure',
                children: [],
              },
              {
                id: 'testing-utilities',
                level: 3,
                text: 'Testing Utilities',
                children: [],
              },
              {
                id: 'example-tests',
                level: 3,
                text: 'Example Tests',
                children: [],
              },
            ],
          },
          {
            id: 'debugging',
            level: 2,
            text: 'Debugging',
            children: [
              {
                id: 'logging',
                level: 3,
                text: 'Logging',
                children: [],
              },
              {
                id: 'debug-configuration',
                level: 3,
                text: 'Debug Configuration',
                children: [],
              },
            ],
          },
          {
            id: 'contributing',
            level: 2,
            text: 'Contributing',
            children: [
              {
                id: 'code-style',
                level: 3,
                text: 'Code Style',
                children: [],
              },
              {
                id: 'commit-guidelines',
                level: 3,
                text: 'Commit Guidelines',
                children: [],
              },
              {
                id: 'pull-request-process',
                level: 3,
                text: 'Pull Request Process',
                children: [],
              },
              {
                id: 'release-process',
                level: 3,
                text: 'Release Process',
                children: [],
              },
            ],
          },
          {
            id: 'performance-benchmarks',
            level: 2,
            text: 'Performance Benchmarks',
            children: [
              {
                id: 'running-benchmarks',
                level: 3,
                text: 'Running Benchmarks',
                children: [],
              },
              {
                id: 'example-benchmark',
                level: 3,
                text: 'Example Benchmark',
                children: [],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    file: 'manifest_builder/storage-providers.mdx',
    path: '/manifest_builder/storage-providers',
    title: 'Storage Providers',
    toc: [
      {
        id: 'storage-providers',
        level: 1,
        text: 'Storage Providers',
        children: [
          {
            id: 'provider-overview',
            level: 2,
            text: 'Provider Overview',
            children: [],
          },
          {
            id: 'amazon-s3-provider',
            level: 2,
            text: 'Amazon S3 Provider',
            children: [
              {
                id: 'basic-configuration',
                level: 3,
                text: 'Basic Configuration',
                children: [],
              },
              {
                id: 'advanced-s3-configuration',
                level: 3,
                text: 'Advanced S3 Configuration',
                children: [],
              },
              {
                id: 's3-compatible-services',
                level: 3,
                text: 'S3-Compatible Services',
                children: [
                  {
                    id: 'digitalocean-spaces',
                    level: 4,
                    text: 'DigitalOcean Spaces',
                    children: [],
                  },
                  {
                    id: 'cloudflare-r2',
                    level: 4,
                    text: 'Cloudflare R2',
                    children: [],
                  },
                  {
                    id: 'minio-self-hosted',
                    level: 4,
                    text: 'MinIO (Self-hosted)',
                    children: [],
                  },
                ],
              },
              {
                id: 's3-performance-optimization',
                level: 3,
                text: 'S3 Performance Optimization',
                children: [],
              },
            ],
          },
          {
            id: 'github-provider',
            level: 2,
            text: 'GitHub Provider',
            children: [
              {
                id: 'basic-configuration',
                level: 3,
                text: 'Basic Configuration',
                children: [],
              },
              {
                id: 'advanced-github-configuration',
                level: 3,
                text: 'Advanced GitHub Configuration',
                children: [],
              },
              {
                id: 'github-large-file-support',
                level: 3,
                text: 'GitHub Large File Support',
                children: [],
              },
            ],
          },
          {
            id: 'local-storage-provider',
            level: 2,
            text: 'Local Storage Provider',
            children: [
              {
                id: 'basic-configuration',
                level: 3,
                text: 'Basic Configuration',
                children: [],
              },
              {
                id: 'advanced-local-configuration',
                level: 3,
                text: 'Advanced Local Configuration',
                children: [],
              },
              {
                id: 'local-development-setup',
                level: 3,
                text: 'Local Development Setup',
                children: [],
              },
            ],
          },
          {
            id: 'provider-specific-features',
            level: 2,
            text: 'Provider-Specific Features',
            children: [
              {
                id: 's3-features',
                level: 3,
                text: 'S3 Features',
                children: [
                  {
                    id: 'cloudfront-integration',
                    level: 4,
                    text: 'CloudFront Integration',
                    children: [],
                  },
                  {
                    id: 'lifecycle-management',
                    level: 4,
                    text: 'Lifecycle Management',
                    children: [],
                  },
                ],
              },
              {
                id: 'github-features',
                level: 3,
                text: 'GitHub Features',
                children: [
                  {
                    id: 'release-integration',
                    level: 4,
                    text: 'Release Integration',
                    children: [],
                  },
                  {
                    id: 'webhook-support',
                    level: 4,
                    text: 'Webhook Support',
                    children: [],
                  },
                ],
              },
            ],
          },
          {
            id: 'migration-between-providers',
            level: 2,
            text: 'Migration Between Providers',
            children: [],
          },
          {
            id: 'performance-comparison',
            level: 2,
            text: 'Performance Comparison',
            children: [],
          },
          {
            id: 'best-practices',
            level: 2,
            text: 'Best Practices',
            children: [
              {
                id: 's3-best-practices',
                level: 3,
                text: 'S3 Best Practices',
                children: [],
              },
              {
                id: 'github-best-practices',
                level: 3,
                text: 'GitHub Best Practices',
                children: [],
              },
              {
                id: 'local-best-practices',
                level: 3,
                text: 'Local Best Practices',
                children: [],
              },
            ],
          },
        ],
      },
    ],
  },
]

// Helper function to find TOC data by file path
export function getTocByFile(filePath: string): TocItem[] | undefined {
  const item = tocData.find((item) => item.file === filePath)
  return item?.toc
}

// Helper function to find TOC data by route path
export function getTocByPath(routePath: string): TocItem[] | undefined {
  const item = tocData.find((item) => item.path === routePath)
  return item?.toc
}

// Helper function to flatten TOC tree into a simple array
export function flattenToc(toc: TocItem[]): TocItem[] {
  const result: TocItem[] = []

  function traverse(items: TocItem[]) {
    for (const item of items) {
      result.push({
        id: item.id,
        level: item.level,
        text: item.text,
      })
      if (item.children && item.children.length > 0) {
        traverse(item.children)
      }
    }
  }

  traverse(toc)
  return result
}

// Helper function to get all headings at a specific level
export function getHeadingsByLevel(toc: TocItem[], level: number): TocItem[] {
  const result: TocItem[] = []

  function traverse(items: TocItem[]) {
    for (const item of items) {
      if (item.level === level) {
        result.push(item)
      }
      if (item.children && item.children.length > 0) {
        traverse(item.children)
      }
    }
  }

  traverse(toc)
  return result
}
