// This file is automatically generated by the toc-extractor plugin
// Do not edit manually

export interface TocItem {
  id: string
  level: number
  text: string
  children?: TocItem[]
}

export interface FileToc {
  file: string
  path: string
  title: string
  toc: TocItem[]
}

export const tocData: FileToc[] = [
  {
    file: 'index.mdx',
    path: '/',
    title: 'Overview',
    toc: [
      {
        id: 'heading-overview',
        level: 1,
        text: 'Overview',
        children: [
          {
            id: 'heading-features',
            level: 2,
            text: '🌟 Features',
            children: [
              {
                id: 'heading-core-functionality',
                level: 3,
                text: 'Core Functionality',
                children: [],
              },
              {
                id: 'heading-image-processing',
                level: 3,
                text: 'Image Processing',
                children: [],
              },
              {
                id: 'heading-advanced-features',
                level: 3,
                text: 'Advanced Features',
                children: [],
              },
            ],
          },
          {
            id: 'heading-technical-architecture',
            level: 2,
            text: '🏗️ Technical Architecture',
            children: [
              {
                id: 'heading-frontend-tech-stack',
                level: 3,
                text: 'Frontend Tech Stack',
                children: [],
              },
              {
                id: 'heading-build-system',
                level: 3,
                text: 'Build System',
                children: [],
              },
              {
                id: 'heading-storage-architecture',
                level: 3,
                text: 'Storage Architecture',
                children: [],
              },
            ],
          },
          {
            id: 'heading-quick-start',
            level: 2,
            text: '🚀 Quick Start',
            children: [
              {
                id: 'heading-docker-deployment',
                level: 3,
                text: 'Docker Deployment',
                children: [],
              },
            ],
          },
          {
            id: 'heading-configuration-options',
            level: 2,
            text: '⚙️ Configuration Options',
            children: [
              {
                id: 'heading-remote-repository-configuration-repo',
                level: 4,
                text: 'Remote Repository Configuration (`repo`)',
                children: [],
              },
              {
                id: 'heading-storage-configuration-storage',
                level: 4,
                text: 'Storage Configuration (`storage`)',
                children: [],
              },
              {
                id: 'heading-build-options-options',
                level: 4,
                text: 'Build Options (`options`)',
                children: [],
              },
              {
                id: 'heading-performance-configuration-performance',
                level: 4,
                text: 'Performance Configuration (`performance`)',
                children: [],
              },
              {
                id: 'heading-logging-configuration-logging',
                level: 4,
                text: 'Logging Configuration (`logging`)',
                children: [],
              },
            ],
          },
          {
            id: 'heading-cli-commands',
            level: 2,
            text: '📋 CLI Commands',
            children: [
              {
                id: 'heading-build-commands',
                level: 3,
                text: 'Build Commands',
                children: [],
              },
              {
                id: 'heading-development-commands',
                level: 3,
                text: 'Development Commands',
                children: [],
              },
              {
                id: 'heading-notes',
                level: 3,
                text: 'Notes',
                children: [],
              },
            ],
          },
          {
            id: 'heading-advanced-usage',
            level: 2,
            text: '🔧 Advanced Usage',
            children: [
              {
                id: 'heading-custom-storage-provider',
                level: 3,
                text: 'Custom Storage Provider',
                children: [],
              },
              {
                id: 'heading-custom-image-processing',
                level: 3,
                text: 'Custom Image Processing',
                children: [],
              },
            ],
          },
          {
            id: 'heading-license',
            level: 2,
            text: '📄 License',
            children: [],
          },
          {
            id: 'heading-related-links',
            level: 2,
            text: '🔗 Related Links',
            children: [],
          },
        ],
      },
    ],
  },
  {
    file: 'apps/index.mdx',
    path: '/apps',
    title: 'Apps Package',
    toc: [
      {
        id: 'heading-apps-package',
        level: 1,
        text: 'Apps Package',
        children: [],
      },
    ],
  },
  {
    file: 'deployment/index.mdx',
    path: '/deployment',
    title: 'Deployment',
    toc: [
      {
        id: 'heading-deployment',
        level: 1,
        text: 'Deployment',
        children: [],
      },
    ],
  },
  {
    file: 'getting-started.md',
    path: '/getting-started',
    title: 'Getting Started',
    toc: [
      {
        id: 'heading-getting-started',
        level: 1,
        text: 'Getting Started',
        children: [
          {
            id: 'heading-features',
            level: 2,
            text: 'Features',
            children: [],
          },
          {
            id: 'heading-quick-start',
            level: 2,
            text: 'Quick Start',
            children: [],
          },
        ],
      },
    ],
  },
  {
    file: 'manifest_builder/index.mdx',
    path: '/manifest_builder',
    title: 'Manifest Builder',
    toc: [
      {
        id: 'heading-manifest-builder',
        level: 1,
        text: 'Manifest Builder',
        children: [
          {
            id: 'heading-core-features',
            level: 2,
            text: 'Core Features',
            children: [
              {
                id: 'heading-photo-processing',
                level: 3,
                text: '📸 Photo Processing',
                children: [],
              },
              {
                id: 'heading-image-analysis',
                level: 3,
                text: '🎨 Image Analysis',
                children: [],
              },
              {
                id: 'heading-storage-support',
                level: 3,
                text: '🗄️ Storage Support',
                children: [],
              },
              {
                id: 'heading-performance-optimization',
                level: 3,
                text: '⚡ Performance Optimization',
                children: [],
              },
            ],
          },
          {
            id: 'heading-architecture-design',
            level: 2,
            text: 'Architecture Design',
            children: [
              {
                id: 'heading-core-modules',
                level: 3,
                text: 'Core Modules',
                children: [],
              },
            ],
          },
          {
            id: 'heading-use-cases',
            level: 2,
            text: 'Use Cases',
            children: [
              {
                id: 'heading-1-photo-library-building',
                level: 3,
                text: '1. Photo Library Building',
                children: [],
              },
              {
                id: 'heading-2-batch-photo-processing',
                level: 3,
                text: '2. Batch Photo Processing',
                children: [],
              },
              {
                id: 'heading-3-storage-migration',
                level: 3,
                text: '3. Storage Migration',
                children: [],
              },
            ],
          },
          {
            id: 'heading-key-features',
            level: 2,
            text: 'Key Features',
            children: [],
          },
          {
            id: 'heading-configuration-example',
            level: 2,
            text: 'Configuration Example',
            children: [],
          },
          {
            id: 'heading-output-format',
            level: 2,
            text: 'Output Format',
            children: [],
          },
        ],
      },
    ],
  },
  {
    file: 'manifest_builder/api-reference.mdx',
    path: '/manifest_builder/api-reference',
    title: 'API Reference',
    toc: [
      {
        id: 'heading-api-reference',
        level: 1,
        text: 'API Reference',
        children: [
          {
            id: 'heading-core-api',
            level: 2,
            text: 'Core API',
            children: [
              {
                id: 'heading-builder-class',
                level: 3,
                text: 'Builder Class',
                children: [
                  {
                    id: 'heading-constructor',
                    level: 4,
                    text: 'Constructor',
                    children: [],
                  },
                  {
                    id: 'heading-methods',
                    level: 4,
                    text: 'Methods',
                    children: [
                      {
                        id: 'heading-buildoptions',
                        level: 5,
                        text: '`build(options?)`',
                        children: [],
                      },
                      {
                        id: 'heading-validateoptions',
                        level: 5,
                        text: '`validate(options?)`',
                        children: [],
                      },
                      {
                        id: 'heading-cleanupoptions',
                        level: 5,
                        text: '`cleanup(options?)`',
                        children: [],
                      },
                    ],
                  },
                ],
              },
            ],
          },
          {
            id: 'heading-configuration-interfaces',
            level: 2,
            text: 'Configuration Interfaces',
            children: [
              {
                id: 'heading-builderconfig',
                level: 3,
                text: 'BuilderConfig',
                children: [],
              },
              {
                id: 'heading-storageconfig',
                level: 3,
                text: 'StorageConfig',
                children: [],
              },
              {
                id: 'heading-performanceconfig',
                level: 3,
                text: 'PerformanceConfig',
                children: [],
              },
            ],
          },
          {
            id: 'heading-photo-processing-api',
            level: 2,
            text: 'Photo Processing API',
            children: [
              {
                id: 'heading-photoprocessor',
                level: 3,
                text: 'PhotoProcessor',
                children: [
                  {
                    id: 'heading-methods',
                    level: 4,
                    text: 'Methods',
                    children: [
                      {
                        id: 'heading-processphotofile-options',
                        level: 5,
                        text: '`processPhoto(file, options?)`',
                        children: [],
                      },
                      {
                        id: 'heading-generatethumbnailsphoto-sizes',
                        level: 5,
                        text: '`generateThumbnails(photo, sizes?)`',
                        children: [],
                      },
                      {
                        id: 'heading-extractmetadatafile',
                        level: 5,
                        text: '`extractMetadata(file)`',
                        children: [],
                      },
                    ],
                  },
                ],
              },
              {
                id: 'heading-image-analysis-api',
                level: 3,
                text: 'Image Analysis API',
                children: [
                  {
                    id: 'heading-thumbhash-generation',
                    level: 4,
                    text: 'ThumbHash Generation',
                    children: [],
                  },
                  {
                    id: 'heading-tone-analysis',
                    level: 4,
                    text: 'Tone Analysis',
                    children: [],
                  },
                  {
                    id: 'heading-histogram-generation',
                    level: 4,
                    text: 'Histogram Generation',
                    children: [],
                  },
                ],
              },
            ],
          },
          {
            id: 'heading-storage-api',
            level: 2,
            text: 'Storage API',
            children: [
              {
                id: 'heading-storage-providers',
                level: 3,
                text: 'Storage Providers',
                children: [],
              },
              {
                id: 'heading-storage-interface',
                level: 3,
                text: 'Storage Interface',
                children: [],
              },
            ],
          },
          {
            id: 'heading-worker-api',
            level: 2,
            text: 'Worker API',
            children: [
              {
                id: 'heading-cluster-processing',
                level: 3,
                text: 'Cluster Processing',
                children: [],
              },
              {
                id: 'heading-thread-pool-processing',
                level: 3,
                text: 'Thread Pool Processing',
                children: [],
              },
            ],
          },
          {
            id: 'heading-manifest-api',
            level: 2,
            text: 'Manifest API',
            children: [
              {
                id: 'heading-manifest-management',
                level: 3,
                text: 'Manifest Management',
                children: [],
              },
              {
                id: 'heading-manifest-schema',
                level: 3,
                text: 'Manifest Schema',
                children: [],
              },
            ],
          },
          {
            id: 'heading-event-system',
            level: 2,
            text: 'Event System',
            children: [
              {
                id: 'heading-available-events',
                level: 3,
                text: 'Available Events',
                children: [],
              },
            ],
          },
          {
            id: 'heading-extensions-and-plugins',
            level: 2,
            text: 'Extensions and Plugins',
            children: [
              {
                id: 'heading-creating-custom-processors',
                level: 3,
                text: 'Creating Custom Processors',
                children: [],
              },
              {
                id: 'heading-creating-storage-providers',
                level: 3,
                text: 'Creating Storage Providers',
                children: [],
              },
            ],
          },
          {
            id: 'heading-utility-functions',
            level: 2,
            text: 'Utility Functions',
            children: [
              {
                id: 'heading-file-utilities',
                level: 3,
                text: 'File Utilities',
                children: [],
              },
              {
                id: 'heading-image-utilities',
                level: 3,
                text: 'Image Utilities',
                children: [],
              },
            ],
          },
          {
            id: 'heading-error-handling',
            level: 2,
            text: 'Error Handling',
            children: [],
          },
          {
            id: 'heading-typescript-support',
            level: 2,
            text: 'TypeScript Support',
            children: [],
          },
        ],
      },
    ],
  },
  {
    file: 'manifest_builder/cli-usage.mdx',
    path: '/manifest_builder/cli-usage',
    title: 'Command Line Usage',
    toc: [
      {
        id: 'heading-command-line-usage',
        level: 1,
        text: 'Command Line Usage',
        children: [
          {
            id: 'heading-basic-commands',
            level: 2,
            text: 'Basic Commands',
            children: [
              {
                id: 'heading-build-command',
                level: 3,
                text: 'Build Command',
                children: [],
              },
              {
                id: 'heading-common-options',
                level: 3,
                text: 'Common Options',
                children: [],
              },
            ],
          },
          {
            id: 'heading-advanced-options',
            level: 2,
            text: 'Advanced Options',
            children: [
              {
                id: 'heading-processing-control',
                level: 3,
                text: 'Processing Control',
                children: [],
              },
              {
                id: 'heading-file-filtering',
                level: 3,
                text: 'File Filtering',
                children: [],
              },
              {
                id: 'heading-output-control',
                level: 3,
                text: 'Output Control',
                children: [],
              },
            ],
          },
          {
            id: 'heading-specialized-commands',
            level: 2,
            text: 'Specialized Commands',
            children: [
              {
                id: 'heading-validation-commands',
                level: 3,
                text: 'Validation Commands',
                children: [],
              },
              {
                id: 'heading-maintenance-commands',
                level: 3,
                text: 'Maintenance Commands',
                children: [],
              },
              {
                id: 'heading-migration-commands',
                level: 3,
                text: 'Migration Commands',
                children: [],
              },
            ],
          },
          {
            id: 'heading-configuration-options',
            level: 2,
            text: 'Configuration Options',
            children: [
              {
                id: 'heading-config-file-selection',
                level: 3,
                text: 'Config File Selection',
                children: [],
              },
              {
                id: 'heading-runtime-configuration',
                level: 3,
                text: 'Runtime Configuration',
                children: [],
              },
            ],
          },
          {
            id: 'heading-monitoring-and-logging',
            level: 2,
            text: 'Monitoring and Logging',
            children: [
              {
                id: 'heading-progress-monitoring',
                level: 3,
                text: 'Progress Monitoring',
                children: [],
              },
              {
                id: 'heading-logging-options',
                level: 3,
                text: 'Logging Options',
                children: [],
              },
            ],
          },
          {
            id: 'heading-examples',
            level: 2,
            text: 'Examples',
            children: [
              {
                id: 'heading-development-workflow',
                level: 3,
                text: 'Development Workflow',
                children: [],
              },
              {
                id: 'heading-production-deployment',
                level: 3,
                text: 'Production Deployment',
                children: [],
              },
              {
                id: 'heading-troubleshooting',
                level: 3,
                text: 'Troubleshooting',
                children: [],
              },
            ],
          },
          {
            id: 'heading-environment-variables',
            level: 2,
            text: 'Environment Variables',
            children: [],
          },
          {
            id: 'heading-exit-codes',
            level: 2,
            text: 'Exit Codes',
            children: [],
          },
          {
            id: 'heading-scripting-and-automation',
            level: 2,
            text: 'Scripting and Automation',
            children: [
              {
                id: 'heading-github-actions-example',
                level: 3,
                text: 'GitHub Actions Example',
                children: [],
              },
              {
                id: 'heading-cron-job-example',
                level: 3,
                text: 'Cron Job Example',
                children: [],
              },
            ],
          },
          {
            id: 'heading-getting-help',
            level: 2,
            text: 'Getting Help',
            children: [],
          },
        ],
      },
    ],
  },
  {
    file: 'manifest_builder/configuration.mdx',
    path: '/manifest_builder/configuration',
    title: 'Configuration Guide',
    toc: [
      {
        id: 'heading-configuration-guide',
        level: 1,
        text: 'Configuration Guide',
        children: [
          {
            id: 'heading-configuration-file-structure',
            level: 2,
            text: 'Configuration File Structure',
            children: [],
          },
          {
            id: 'heading-storage-configuration',
            level: 2,
            text: 'Storage Configuration',
            children: [
              {
                id: 'heading-amazon-s3-configuration',
                level: 3,
                text: 'Amazon S3 Configuration',
                children: [],
              },
              {
                id: 'heading-github-storage-configuration',
                level: 3,
                text: 'GitHub Storage Configuration',
                children: [],
              },
              {
                id: 'heading-local-storage-configuration',
                level: 3,
                text: 'Local Storage Configuration',
                children: [],
              },
            ],
          },
          {
            id: 'heading-performance-configuration',
            level: 2,
            text: 'Performance Configuration',
            children: [
              {
                id: 'heading-worker-configuration',
                level: 3,
                text: 'Worker Configuration',
                children: [],
              },
              {
                id: 'heading-optimization-settings',
                level: 3,
                text: 'Optimization Settings',
                children: [],
              },
            ],
          },
          {
            id: 'heading-general-options',
            level: 2,
            text: 'General Options',
            children: [
              {
                id: 'heading-feature-toggles',
                level: 3,
                text: 'Feature Toggles',
                children: [],
              },
              {
                id: 'heading-path-configuration',
                level: 3,
                text: 'Path Configuration',
                children: [],
              },
            ],
          },
          {
            id: 'heading-environment-specific-configurations',
            level: 2,
            text: 'Environment-Specific Configurations',
            children: [
              {
                id: 'heading-development-configuration',
                level: 3,
                text: 'Development Configuration',
                children: [],
              },
              {
                id: 'heading-production-configuration',
                level: 3,
                text: 'Production Configuration',
                children: [],
              },
            ],
          },
          {
            id: 'heading-configuration-validation',
            level: 2,
            text: 'Configuration Validation',
            children: [],
          },
          {
            id: 'heading-environment-variables',
            level: 2,
            text: 'Environment Variables',
            children: [],
          },
          {
            id: 'heading-configuration-best-practices',
            level: 2,
            text: 'Configuration Best Practices',
            children: [],
          },
        ],
      },
    ],
  },
  {
    file: 'manifest_builder/development.mdx',
    path: '/manifest_builder/development',
    title: 'Development Guide',
    toc: [
      {
        id: 'heading-development-guide',
        level: 1,
        text: 'Development Guide',
        children: [
          {
            id: 'heading-development-setup',
            level: 2,
            text: 'Development Setup',
            children: [
              {
                id: 'heading-prerequisites',
                level: 3,
                text: 'Prerequisites',
                children: [],
              },
              {
                id: 'heading-environment-setup',
                level: 3,
                text: 'Environment Setup',
                children: [],
              },
              {
                id: 'heading-development-scripts',
                level: 3,
                text: 'Development Scripts',
                children: [],
              },
            ],
          },
          {
            id: 'heading-project-structure',
            level: 2,
            text: 'Project Structure',
            children: [],
          },
          {
            id: 'heading-architecture-overview',
            level: 2,
            text: 'Architecture Overview',
            children: [
              {
                id: 'heading-core-components',
                level: 3,
                text: 'Core Components',
                children: [
                  {
                    id: 'heading-1-builder-core-srcbuilder',
                    level: 4,
                    text: '1. Builder Core (`src/builder/`)',
                    children: [],
                  },
                  {
                    id: 'heading-2-storage-layer-srcstorage',
                    level: 4,
                    text: '2. Storage Layer (`src/storage/`)',
                    children: [],
                  },
                  {
                    id: 'heading-3-photo-processing-srcphoto',
                    level: 4,
                    text: '3. Photo Processing (`src/photo/`)',
                    children: [],
                  },
                  {
                    id: 'heading-4-image-analysis-srcimage',
                    level: 4,
                    text: '4. Image Analysis (`src/image/`)',
                    children: [],
                  },
                  {
                    id: 'heading-5-worker-management-srcworker',
                    level: 4,
                    text: '5. Worker Management (`src/worker/`)',
                    children: [],
                  },
                ],
              },
              {
                id: 'heading-data-flow',
                level: 3,
                text: 'Data Flow',
                children: [],
              },
            ],
          },
          {
            id: 'heading-development-workflows',
            level: 2,
            text: 'Development Workflows',
            children: [
              {
                id: 'heading-adding-a-new-storage-provider',
                level: 3,
                text: 'Adding a New Storage Provider',
                children: [],
              },
              {
                id: 'heading-adding-image-analysis-features',
                level: 3,
                text: 'Adding Image Analysis Features',
                children: [],
              },
              {
                id: 'heading-performance-optimization',
                level: 3,
                text: 'Performance Optimization',
                children: [
                  {
                    id: 'heading-profiling',
                    level: 4,
                    text: 'Profiling',
                    children: [],
                  },
                  {
                    id: 'heading-memory-management',
                    level: 4,
                    text: 'Memory Management',
                    children: [],
                  },
                ],
              },
            ],
          },
          {
            id: 'heading-testing',
            level: 2,
            text: 'Testing',
            children: [
              {
                id: 'heading-test-structure',
                level: 3,
                text: 'Test Structure',
                children: [],
              },
              {
                id: 'heading-testing-utilities',
                level: 3,
                text: 'Testing Utilities',
                children: [],
              },
              {
                id: 'heading-example-tests',
                level: 3,
                text: 'Example Tests',
                children: [],
              },
            ],
          },
          {
            id: 'heading-debugging',
            level: 2,
            text: 'Debugging',
            children: [
              {
                id: 'heading-logging',
                level: 3,
                text: 'Logging',
                children: [],
              },
              {
                id: 'heading-debug-configuration',
                level: 3,
                text: 'Debug Configuration',
                children: [],
              },
            ],
          },
          {
            id: 'heading-contributing',
            level: 2,
            text: 'Contributing',
            children: [
              {
                id: 'heading-code-style',
                level: 3,
                text: 'Code Style',
                children: [],
              },
              {
                id: 'heading-commit-guidelines',
                level: 3,
                text: 'Commit Guidelines',
                children: [],
              },
              {
                id: 'heading-pull-request-process',
                level: 3,
                text: 'Pull Request Process',
                children: [],
              },
              {
                id: 'heading-release-process',
                level: 3,
                text: 'Release Process',
                children: [],
              },
            ],
          },
          {
            id: 'heading-performance-benchmarks',
            level: 2,
            text: 'Performance Benchmarks',
            children: [
              {
                id: 'heading-running-benchmarks',
                level: 3,
                text: 'Running Benchmarks',
                children: [],
              },
              {
                id: 'heading-example-benchmark',
                level: 3,
                text: 'Example Benchmark',
                children: [],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    file: 'manifest_builder/storage-providers.mdx',
    path: '/manifest_builder/storage-providers',
    title: 'Storage Providers',
    toc: [
      {
        id: 'heading-storage-providers',
        level: 1,
        text: 'Storage Providers',
        children: [
          {
            id: 'heading-provider-overview',
            level: 2,
            text: 'Provider Overview',
            children: [],
          },
          {
            id: 'heading-amazon-s3-provider',
            level: 2,
            text: 'Amazon S3 Provider',
            children: [
              {
                id: 'heading-basic-configuration',
                level: 3,
                text: 'Basic Configuration',
                children: [],
              },
              {
                id: 'heading-advanced-s3-configuration',
                level: 3,
                text: 'Advanced S3 Configuration',
                children: [],
              },
              {
                id: 'heading-s3-compatible-services',
                level: 3,
                text: 'S3-Compatible Services',
                children: [
                  {
                    id: 'heading-digitalocean-spaces',
                    level: 4,
                    text: 'DigitalOcean Spaces',
                    children: [],
                  },
                  {
                    id: 'heading-cloudflare-r2',
                    level: 4,
                    text: 'Cloudflare R2',
                    children: [],
                  },
                  {
                    id: 'heading-minio-self-hosted',
                    level: 4,
                    text: 'MinIO (Self-hosted)',
                    children: [],
                  },
                ],
              },
              {
                id: 'heading-s3-performance-optimization',
                level: 3,
                text: 'S3 Performance Optimization',
                children: [],
              },
            ],
          },
          {
            id: 'heading-github-provider',
            level: 2,
            text: 'GitHub Provider',
            children: [
              {
                id: 'heading-basic-configuration',
                level: 3,
                text: 'Basic Configuration',
                children: [],
              },
              {
                id: 'heading-advanced-github-configuration',
                level: 3,
                text: 'Advanced GitHub Configuration',
                children: [],
              },
              {
                id: 'heading-github-large-file-support',
                level: 3,
                text: 'GitHub Large File Support',
                children: [],
              },
            ],
          },
          {
            id: 'heading-local-storage-provider',
            level: 2,
            text: 'Local Storage Provider',
            children: [
              {
                id: 'heading-basic-configuration',
                level: 3,
                text: 'Basic Configuration',
                children: [],
              },
              {
                id: 'heading-advanced-local-configuration',
                level: 3,
                text: 'Advanced Local Configuration',
                children: [],
              },
              {
                id: 'heading-local-development-setup',
                level: 3,
                text: 'Local Development Setup',
                children: [],
              },
            ],
          },
          {
            id: 'heading-provider-specific-features',
            level: 2,
            text: 'Provider-Specific Features',
            children: [
              {
                id: 'heading-s3-features',
                level: 3,
                text: 'S3 Features',
                children: [
                  {
                    id: 'heading-cloudfront-integration',
                    level: 4,
                    text: 'CloudFront Integration',
                    children: [],
                  },
                  {
                    id: 'heading-lifecycle-management',
                    level: 4,
                    text: 'Lifecycle Management',
                    children: [],
                  },
                ],
              },
              {
                id: 'heading-github-features',
                level: 3,
                text: 'GitHub Features',
                children: [
                  {
                    id: 'heading-release-integration',
                    level: 4,
                    text: 'Release Integration',
                    children: [],
                  },
                  {
                    id: 'heading-webhook-support',
                    level: 4,
                    text: 'Webhook Support',
                    children: [],
                  },
                ],
              },
            ],
          },
          {
            id: 'heading-migration-between-providers',
            level: 2,
            text: 'Migration Between Providers',
            children: [],
          },
          {
            id: 'heading-performance-comparison',
            level: 2,
            text: 'Performance Comparison',
            children: [],
          },
          {
            id: 'heading-best-practices',
            level: 2,
            text: 'Best Practices',
            children: [
              {
                id: 'heading-s3-best-practices',
                level: 3,
                text: 'S3 Best Practices',
                children: [],
              },
              {
                id: 'heading-github-best-practices',
                level: 3,
                text: 'GitHub Best Practices',
                children: [],
              },
              {
                id: 'heading-local-best-practices',
                level: 3,
                text: 'Local Best Practices',
                children: [],
              },
            ],
          },
        ],
      },
    ],
  },
]

// Helper function to find TOC data by file path
export function getTocByFile(filePath: string): TocItem[] | undefined {
  const item = tocData.find((item) => item.file === filePath)
  return item?.toc
}

// Helper function to find TOC data by route path
export function getTocByPath(routePath: string): TocItem[] | undefined {
  const item = tocData.find((item) => item.path === routePath)
  return item?.toc
}

// Helper function to flatten TOC tree into a simple array
export function flattenToc(toc: TocItem[]): TocItem[] {
  const result: TocItem[] = []

  function traverse(items: TocItem[]) {
    for (const item of items) {
      result.push({
        id: item.id,
        level: item.level,
        text: item.text,
      })
      if (item.children && item.children.length > 0) {
        traverse(item.children)
      }
    }
  }

  traverse(toc)
  return result
}

// Helper function to get all headings at a specific level
export function getHeadingsByLevel(toc: TocItem[], level: number): TocItem[] {
  const result: TocItem[] = []

  function traverse(items: TocItem[]) {
    for (const item of items) {
      if (item.level === level) {
        result.push(item)
      }
      if (item.children && item.children.length > 0) {
        traverse(item.children)
      }
    }
  }

  traverse(toc)
  return result
}
